# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U-mH15zrvg1Kax-6WX-qCh8h2ynUfRGT
"""



"""**list **example**"""

mylist=[5.69,"digital",3,"name"]
print('The values are',mylist)
# Index number -> helps to print individual data

#update
mylist[1]="monika"
print('after updating the value',mylist)
#append
mylist.append(55)
print('after updating the value',mylist)
#insert
mylist.insert(3,"ram")
print('after inserting the value',mylist)
#delete

del mylist[-2]
print("The values are",mylist)

"""list **example2**

"""

mylist=["ram",8.57,True,1]
print('The values are',mylist)

#update
mylist[1]="sita"
print('after updating the value',mylist)

#append
mylist.append(68)
print('after updating the value',mylist)

#insert
mylist.insert(1,"gita")
print('after inserting the value',mylist)
#delete

del mylist[-2]
print("The values are",mylist)

"""**tupple**

"""

tuple
mytuple=("adventure",1,1.28)
print(mytuple)
a=[10,20]
b=int(input("Enter the value"))
# a.append(b)
a.insert(1,b)
print(a)



"""**dictionary**"""

thisdict = {
  "brand": "tokyotalkies",
  "style": "sleeved",
  "colour":"gereen"
}
print(thisdict["brand"])
thisdict["colour"]="red"
print(thisdict)
thisdict["style"]="coloured"
print(thisdict)


del thisdict["brand"]
print(thisdict)





"""example **2**"""

thisdict ={
  "name": "monika",
  "class": "ml",
  "rollno":2004325
}
print(thisdict["name"])
thisdict["name"]="tiwary"
print(thisdict)
#update
thisdict.update({"rollno":2004294})
print(thisdict)
#add
thisdict.update({"section":"three"})
print(thisdict)
#access
x=thisdict.get("name")
print(x)
del thisdict({"class":"ml"})
print(thisdict)

"""**set**"""

#example1

myset1 = {"apple", "banana", "cherry"}
myset2={1,2,3}
print(myset1)
myset1.add(100)
print(myset1)
myset1.remove("banana")
print(myset1)
myset3=myset1.union(myset2)
print(myset3)

