# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HbZ95vQK2jK5zAf4qyXl8EdyIis-_iJr
"""

thisfile=open("m.txt","r")
print(thisfile.read())

thisfile.close()

thisfile=open("m.txt","w+")
thisfile.write("this is written by me \n")

thisfile=open("m.txt","r+")
print(thisfile.read())

thisfile=open("a.txt","a")
thisfile.write("this is written by mt \n")



thisfile=open("m.txt","r")
print(thisfile.read())

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    return x / y


print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")

while True:
  
    choice = input("Enter choice(1/2/3/4): ")

    
    if choice in ('1', '2', '3', '4'):
        try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
        except ValueError:
            print("Invalid input. Please enter a number.")
            continue

        if choice == '1':
            print(num1, "+", num2, "=", add(num1, num2))

        elif choice == '2':
            print(num1, "-", num2, "=", subtract(num1, num2))

        elif choice == '3':
            print(num1, "*", num2, "=", multiply(num1, num2))

        elif choice == '4':
            print(num1, "/", num2, "=", divide(num1, num2))
        

      
        next_calculation = input(" calculation? (yes/no): ")
        if next_calculation == "no":
          break
    else:
        print("Invalid Input")